---
apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
spec:
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                # 6
    spec:
      containers:
        - image: acelee/sentiment-analysis-frontend
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: sa-logic
spec:
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-logic                                # 6
    spec:
      containers:
        - image: rinormaloku/sentiment-analysis
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000
---
apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: sa-web-app
spec:
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-web-app                                # 6
    spec:
      containers:
        - image: rinormaloku/sentiment-analysis-web-app
          imagePullPolicy: Always
          name: sa-web-app
          env:
            - name: SA_LOGIC_API_URL
              # value: "http://localhost:5000"
              value: "http://sa-logic"
          ports:
            - containerPort: 8080
