apiVersion: v1
kind: Service              # 1
metadata:
  name: sa-deployment-np
spec:
  type: NodePort           # 2
  ports:
  - port: 80               # 3
    name: frontend
    protocol: TCP          # 4
    targetPort: 80         # 5
  - port: 8080               # 3
    name: webapp
    protocol: TCP          # 4
    targetPort: 8080         # 5
    nodePort: 30030
  selector:                # 6
    app: sa-deployment     # 7
