---
apiVersion: v1
kind: Service              # 1
metadata:
  name: sa-frontend-np
spec:
  type: NodePort           # 2
  ports:
  - port: 80               # 3
    name: frontend
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: sa-frontend       # 7
---
apiVersion: v1
kind: Service
metadata:
  name: sa-web-app-np
spec:
  type: NodePort           # 2
  ports:
  - port: 8080             # 3
    name: webapp
    protocol: TCP          # 4
    targetPort: 8080       # 5
    nodePort: 30030
  selector:                # 6
    app: sa-web-app        # 7
---
apiVersion: v1
kind: Service
metadata:
  name: sa-logic
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: sa-logic
